%% HW 2 Solutions
% APSC 1001
% Randy Schur

clear
close all

%% Problem 1

%Given:
data = csvread('Data_HW2.csv', 1,0);
x1 = data(:,1);
y1 = data(:,2);

x2 = data(1:100, 4);
y2 = data(1:100, 5);

plot(x1,y1)
figure
plot(x2, y2)

%First Curve
a1 = 0.1884; %values from cftool
b1 = 6.28;
c1 = 1.571;
%R-square value is 1

f1 = @(s) a1*sin(b1*s+c1);  %function generated by cftool
y1_generated = f1(x1); %curve fit data
figure
plot(x1, y1, 'rx')  %plot given data
hold on
plot(x1, y1_generated, 'b-') %plot generated curve
title('Data Set 1')
xlabel('Time (s)')
ylabel('Amplitude (m)')
legend('sampled data', 'generated curve fit')

%Second Curve
p1=6.01; %values from cftool
p2 = 2.246;
p3 = 25.09;
%R-square value is 0.9999

f2 = @(s) p1*s.^2 + p2*s + p3;  %function generated by cftool
y2_generated = f2(x2); %curve fit data
figure
plot(x2, y2, 'rx')  %plot given data
hold on
plot(x2, y2_generated, 'b-') %plot generated curve
title('Data Set 2')
xlabel('Time (s)')
ylabel('Distance Dropped (m)')
legend('sampled data', 'generated curve fit')

%The first curve is data sampled from a vibrating beam in steady state which is being
%excited by a motor.
%The second curve could be the distance fallen by an object over time.